name: CI
on:
  push:
  pull_request:
  merge_group:

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { ruby_version: 3.2 }
          - { ruby_version: 3.3 }
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby_version }}

      - name: Run specs
        run: |
          bundle install --jobs 4 --retry 3 --no-cache
          bundle exec rspec

      - uses: coverallsapp/github-action@v2
        with:
          flag-name: ruby-${{ join(matrix.*, '-') }}
          parallel: true

  coveralls:
    needs: rspec
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

